# Generated by Django 4.0.5 on 2022-06-15 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('vol_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('word', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
    ]
