# Generated by Django 4.0.5 on 2022-06-19 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='chinese',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
